# Generated by Django 2.2.3 on 2019-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherproduct',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
