# Generated by Django 2.2.3 on 2019-12-15 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='test name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='test', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+01789416541'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
