# Generated by Django 2.2.3 on 2019-12-15 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191216_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address1',
            field=models.CharField(blank=True, default='test', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address2',
            field=models.CharField(blank=True, default='test', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, default='+01456433', max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+01789416541'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
